#!/bin/bash
(
cat << EOF
set timeout=5
menuentry 'Auto Install $2 Min UEFI' {
        linuxefi /uefi/../images/$2/$3/vmlinuz ip=dhcp inst.repo=http://$1/os/$2/$3 inst.ks=http://$1/kickstarts/$2_$3_ks.cfg ksdevice=$4
        initrdefi /uefi/../images/$2/$3/initrd.img
}
menuentry 'Manual Install $2 Min UEFI' {
        linuxefi /uefi/../images/$2/$3/vmlinuz ip=dhcp inst.repo=http://$1/os/$2/$3 ksdevice=$4
        initrdefi /uefi/../images/$2/$3/initrd.img
}
EOF
) > /var/lib/tftpboot/uefi/grub.cfg
echo -e "/var/lib/tftpboot/uefi/grub.cfg is create \033[32mSuccessful\033[0m"

